### REQUIRED

namespace: nginx
name: nginx_controller
version: 0.3.1
readme: README.md
authors:
- brianehlert
dependencies: {}
license:
- Apache-2.0-or-later
tags:
- nginx
- controller
- nginxplus
- nginx-plus

description: Supporting NGINX Controller 3.x and later in your pipelines.
repository: https://github.com/nginxinc/ansible-collection-nginx_controller
documentation: https://docs.nginx.com/nginx-controller/
issues: https://github.com/nginxinc/ansible-collection-nginx_controller/issues
