# ansible-playbook nginx_controller_license.yaml -i controller -e '{"controller":{ "user_email":"user@company.com","user_password":"notsecure", "fqdn": "controller.example.local", "validate_certs":false }}'
# ansible-playbook nginx_controller_license.yaml -e "@nginx_install_controller_vars.yaml"

- hosts: localhost
  gather_facts: no

  vars:
    # base64 encoded, one line, no line endings or carriage returns
    license: "{{ lookup('file', 'license/controller_license.base64.txt') }}"

  tasks:
  ## Generate Controller token
  - include_role:
      name: nginxinc.nginx_controller_generate_token

  ## Upload and test license
  - include_role:
      name: nginxinc.nginx_controller_license
