---
# ansible-playbook nginx_controller_agent_3x.yaml -i loadbalancers -e '{"controller":{ "user_email":"user@company.com","user_password":"notsecure", "fqdn": "controller.example.local", "validate_certs":false }}'
# ansible-playbook nginx_controller_agent_3x.yaml -e "@nginx_install_controller_vars.yaml"

- hosts: loadbalancers
  remote_user: ubuntu
  become: true
  become_method: sudo
  gather_facts: yes

  tasks:
  - name: install minimal support for python2 for Agent install script
    apt:
      name: "{{ packages }}"
      state: present
    vars:
      packages:
      - python-minimal
      - libxerces-c3.2

  - include_role:
      name: nginxinc.nginx_controller_generate_token

  - name: Get controller api key for agent registration
    uri:
      url: "https://{{ controller.fqdn }}/api/v1/platform/global"
      method: "GET"
      return_content: yes
      status_code: 200
      validate_certs: "{{ controller.validate_certs | default(false) }}"
      headers:
        Cookie: "{{ controller.auth_token }}"
    register: ctrl_globals

  - name: Copy api_key to a variable
    set_fact:
      api_key: "{{ ctrl_globals.json.currentStatus.agentSettings.apiKey }}"

  - name: install the agent
    include_role:
      name: nginxinc.nginx_controller_agent
